' Gambas module file

Public log As File

Public RutaLog As String = M_Var_Global.sDir
Public Const ERROR_COMUN As String = "ERROR_COMUN"
Public Const ERROR_IMPORTANTE As String = "ERROR_IMPORTANTE"
Public Const ERROR_GRAVE As String = "ERROR_GRAVE"
Public Const REGISTRO As String = "REGISTRO"
Public Const ADVERTENCIA As String = "ADVERTENCIA"

Public Sub Activar() 
  
  If Not Exist(RutaLog &/ "logsInnova") Then
    BorrarRegistros()
  Else
    ComprobarVersion
  Endif
  
Catch
  Message.Error(Error.Text & gb.NewLine & Error.Where)
  
End

Public Sub Agregar(fecha As Date, importancia As String, mensaje As String, Optional donde As String, Optional codigo As String)
  
  ComprobarVersion()
  
  log = Open RutaLog &/ "logsInnova" For Append
  Print #log, Format(fecha, "dd/mm/yyyy hh:mm:ss") & " | " & importancia & " | " & mensaje & " | " & donde & " | " & codigo
  Close #log
  
Catch
  Message.Error(Error.Text & gb.NewLine & Error.Where)
  
End

Public Sub BorrarRegistros()
  
  log = Open RutaLog &/ "logsInnova" For Create
  Print #log, "#" & Application.Version
  Close #log
  
Catch
  Message.Error(Error.Text & gb.NewLine & Error.Where)
  
End

Public Sub ComprobarVersion()
  
  Dim Linea1 As String
  
  log = Open RutaLog &/ "logsVisor" For Read
  
  While Not Eof(log)
    Line Input #log, Linea1
    Break
  Wend
  
  Close #log
  
  Linea1 = Replace(Linea1, gb.NewLine, "")
  
  If Not Left(Linea1) = "#" Then
    Kill RutaLog &/ "logsInnova"
    Activar()
  Else
    If InStr(Right(Linea1, -1), Application.Version) = 0 Then
      Shell "mv -f " & RutaLog &/ "logsInnova" & " " & RutaLog &/ "logsInnova.old"
      Wait 0.2
      Activar()
    Endif
  Endif
  
Catch
  'Message.Error(Error.Text & gb.NewLine & Error.Where)
  
End

Public Sub ObtenerDatosParaTabla() As String[]
  
  Dim Linea As String
  Dim Datos As String[]
  Dim Datos2 As New String[]
  
  log = Open RutaLog &/ "logsInnova" For Read
  
  While Not Eof(log)
    Line Input #log, Linea
    If Left(Linea) = "#" Then Continue
    Datos = Split(Linea, "|", Null, True)
    If Datos.Count <> 5 Then Continue
    Datos2.Add(Linea)
    Linea = ""
    Datos = New String[]
  Wend
  
  Close #log
  
  Return Datos2
  
End
