' Gambas module file

' Gambas class file

' Innova Project 
' Copyright (C) Herberth Guzmán
' herberthguzman@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Public cx As Connection
Public rs As Result
Public Settings_Core_Innova As New Settings(Desktop.ConfigDir &/ "Innova/Innova_Config.conf")
Public Settings_Core_Innova_Usr As New Settings("/usr/share/Innova/Innova_Config.conf")
Private iResult As Integer

Public Sub Init_00()
  
  Dim sResult1 As String
  Dim sResult2 As String
  Dim sSend As String = Desktop.ConfigDir 
  Dim sOrigen As String = "/usr/share/Innova/"
  Dim sCopy As String
  
  Try sResult1 = Settings_Core_Innova["Innova/Version"]
  Try sResult2 = Settings_Core_Innova_Usr["Innova/Version"]
  
  If (sResult1 = sResult2) Then
    Init_01
  Else
    Shell "rm -r " & sSend &/ "Innova"
    Wait 0.9
    Inc Application.Busy
    
    sCopy = "cp -r " & sOrigen & " " & sSend 
    Shell sCopy Wait
    Wait 0.9
    Dec Application.Busy
    Init_01
  Endif 
  
  'Catch
  
End

Public Sub Init_01()
  
  Dim O_Window As String
  
  M_Theme.IconTheme
  M_Theme.Show_Theme
  M_Core.Show_Windows_Manager
  
  Init_02
Catch
  
End

Public Sub Init_02()
  
  f_splash.Show 
  
  Wait 2
  f_splash.Close
  Wait 0.2
  Application.Env["XDG_CURRENT_DESKTOP"] = "Innova"
  
  M_Theme.Show_Theme
  Init_03
  
End

Public Sub Init_03()
  
  Dim sApplets As String[]
  Dim sApplet As String
  
  Dim sExec As String
  
  f_panel.Show
  
  Wait 0.2
  f_wallpaper.Show
  X11.SetWindowProperty(f_wallpaper.Id, Atom["_NET_WM_WINDOW_TYPE"], Atom["ATOM"], Atom["_NET_WM_WINDOW_TYPE_DESKTOP"])
  
  Wait 0.2
  Init_04
End

Public Sub Init_04()
  
  Dim sApplets As String[]
  Dim sApplet As String
  
  Dim sExec As String
  
  cx = M_DB.Connect()
  rs = cx.Exec("SELECT * FROM tb_extensions where status LIKE '1'")
  
  Do While rs.Available 
    sExec = rs!exec
    sApplets = Split(rs!exec, ",")
    rs.MoveNext 
    
    Shell sExec & " > /dev/null 2>/dev/null"
    
    Wait 0.1
  Loop 
  
Catch
  
End
