' Gambas module file

' Innova Project 
' Copyright (C) Herberth Guzmán
' herberthguzman@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Private $Con As New Connection 

Public Procedure Connect() As Connection
  
  $Con = New Connection
  $Con.Type = "sqlite3"
  ' conector.Host = (Application.Path &/ "DB/")
  $Con.Host = (Desktop.ConfigDir &/ "Innova/")
  $Con.Name = "DBInnova.dat"
  Try $Con.Open()
  Return $Con
  
  If Error Then
    Message.Error("Error DB Theme")
    $Con = Null
    Return True 
  End If
  
  Return False 
  
  'Catch
  '  Debug "ERROR [ " & DConv(Error.Text) & " ]" 
  
End

Public Sub Main()
  
  M_Init.Init_01
  
End

Public Sub Close($Con As Connection)
  
  $Con.Close
  $Con = Null
  
End
