' Gambas module file

' Innova Project 
' Copyright (C) Herberth Guzmán
' herberthguzman@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop
' This code belongs to Fabien Bodard and was adapted for Innova Project

Public Sub Add(hForm As Form)
  
  Dim hObs As New Observer(hForm) As "OBS"
  
Catch
  Debug "ERROR [ " & DConv(Error.Text) & " ]"
  
End

Public Sub OBS_KeyPress()
  
  If (Key.Code = Key.Esc) Then
    f_launcher_mini.Close
    f_launcher.Close
  Endif
  ' If (Key.Code = Key.F1) Then f_help.Show
  ' If Key.Code = "16777250" Then 
  'Select Case Key.code 
  '  Case Asc("a") To Asc("z") 
  ' If Key.Code = Asc("a") To Asc("z")  
  
  ' End Select
  
  If (key.Code) Then
    f_launcher_mini.txtSearchApps.SetFocus
    f_launcher.txtSearchApps.SetFocus
  End If
  
  ''  If (Key.Code = Key.F2 And Key.Alt) Then f_widget_eject.Show
  
  'Catch
  '  Debug "ERROR [ " & DConv(Error.Text) & " ]"
  
End
